        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 26 14:07:34 2014
        MODULE SUB_HY_EULER__genmod
          INTERFACE 
            SUBROUTINE SUB_HY_EULER(X)
              REAL(KIND=8), INTENT(OUT) :: X(2)
            END SUBROUTINE SUB_HY_EULER
          END INTERFACE 
        END MODULE SUB_HY_EULER__genmod
