        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 26 14:07:36 2014
        MODULE SUB_EXO__genmod
          INTERFACE 
            SUBROUTINE SUB_EXO
            END SUBROUTINE SUB_EXO
          END INTERFACE 
        END MODULE SUB_EXO__genmod
