        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 26 14:07:35 2014
        MODULE SUB_ENDO_CONSTRAINT__genmod
          INTERFACE 
            SUBROUTINE SUB_ENDO_CONSTRAINT(XB)
              REAL(KIND=8) :: XB
            END SUBROUTINE SUB_ENDO_CONSTRAINT
          END INTERFACE 
        END MODULE SUB_ENDO_CONSTRAINT__genmod
