        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 26 14:07:36 2014
        MODULE SUB_HY_CONSTRAINT__genmod
          INTERFACE 
            SUBROUTINE SUB_HY_CONSTRAINT(XB)
              REAL(KIND=8) :: XB
            END SUBROUTINE SUB_HY_CONSTRAINT
          END INTERFACE 
        END MODULE SUB_HY_CONSTRAINT__genmod
