        !COMPILER-GENERATED INTERFACE MODULE: Wed Feb 26 14:07:34 2014
        MODULE TRIANGULATION__genmod
          INTERFACE 
            SUBROUTINE TRIANGULATION
            END SUBROUTINE TRIANGULATION
          END INTERFACE 
        END MODULE TRIANGULATION__genmod
