        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 25 10:58:51 2014
        MODULE DELAUNAY_INT_BASIS__genmod
          INTERFACE 
            SUBROUTINE DELAUNAY_INT_BASIS(XDASH,HDASH,CDASH,KDASH,VXDASH&
     &,VHDASH,VFDASH)
              REAL(KIND=8) :: XDASH
              REAL(KIND=8) :: HDASH
              REAL(KIND=8), INTENT(OUT) :: CDASH
              REAL(KIND=8), INTENT(OUT) :: KDASH
              REAL(KIND=8), INTENT(OUT) :: VXDASH
              REAL(KIND=8), INTENT(OUT) :: VHDASH
              REAL(KIND=8), INTENT(OUT) :: VFDASH
            END SUBROUTINE DELAUNAY_INT_BASIS
          END INTERFACE 
        END MODULE DELAUNAY_INT_BASIS__genmod
