        !COMPILER-GENERATED INTERFACE MODULE: Fri Dec 16 17:30:57 2011
        MODULE DELAUNAY__genmod
          INTERFACE 
            SUBROUTINE DELAUNAY(XDASH,HDASH,VXDASH,VHDASH)
              REAL(KIND=8), INTENT(IN) :: XDASH
              REAL(KIND=8), INTENT(IN) :: HDASH
              REAL(KIND=8), INTENT(OUT) :: VXDASH
              REAL(KIND=8), INTENT(OUT) :: VHDASH
            END SUBROUTINE DELAUNAY
          END INTERFACE 
        END MODULE DELAUNAY__genmod
