        !COMPILER-GENERATED INTERFACE MODULE: Mon Dec 19 14:18:27 2011
        MODULE DELAUNAY_ME__genmod
          INTERFACE 
            SUBROUTINE DELAUNAY_ME(XDASH,HDASH,VXDASH,VHDASH)
              REAL(KIND=8), INTENT(IN) :: XDASH
              REAL(KIND=8), INTENT(IN) :: HDASH
              REAL(KIND=4), INTENT(OUT) :: VXDASH
              REAL(KIND=4), INTENT(OUT) :: VHDASH
            END SUBROUTINE DELAUNAY_ME
          END INTERFACE 
        END MODULE DELAUNAY_ME__genmod
