        !COMPILER-GENERATED INTERFACE MODULE: Sun May 13 14:56:25 2012
        MODULE SUB_EXO_ONEDIM__genmod
          INTERFACE 
            SUBROUTINE SUB_EXO_ONEDIM(XB)
              REAL(KIND=4) :: XB
            END SUBROUTINE SUB_EXO_ONEDIM
          END INTERFACE 
        END MODULE SUB_EXO_ONEDIM__genmod
