        !COMPILER-GENERATED INTERFACE MODULE: Wed Aug 07 11:25:36 2013
        MODULE SUB_HY_ERR__genmod
          INTERFACE 
            SUBROUTINE SUB_HY_ERR(MEEE_C_FIN,MEEE_K_FIN,AEEE_C_FIN,     &
     &AEEE_K_FIN)
              REAL(KIND=8), INTENT(OUT) :: MEEE_C_FIN
              REAL(KIND=8), INTENT(OUT) :: MEEE_K_FIN
              REAL(KIND=8), INTENT(OUT) :: AEEE_C_FIN
              REAL(KIND=8), INTENT(OUT) :: AEEE_K_FIN
            END SUBROUTINE SUB_HY_ERR
          END INTERFACE 
        END MODULE SUB_HY_ERR__genmod
