        !COMPILER-GENERATED INTERFACE MODULE: Thu Feb 23 14:06:50 2012
        MODULE SUB_HYEXO_ONEDIM__genmod
          INTERFACE 
            SUBROUTINE SUB_HYEXO_ONEDIM(XB)
              REAL(KIND=4) :: XB
            END SUBROUTINE SUB_HYEXO_ONEDIM
          END INTERFACE 
        END MODULE SUB_HYEXO_ONEDIM__genmod
