        !COMPILER-GENERATED INTERFACE MODULE: Wed Jun 05 16:44:06 2013
        MODULE SUB_HI_CONSTRAINT__genmod
          INTERFACE 
            SUBROUTINE SUB_HI_CONSTRAINT(XB)
              REAL(KIND=8) :: XB
            END SUBROUTINE SUB_HI_CONSTRAINT
          END INTERFACE 
        END MODULE SUB_HI_CONSTRAINT__genmod
