        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 25 10:58:50 2014
        MODULE SUB_ENDO_EULER__genmod
          INTERFACE 
            SUBROUTINE SUB_ENDO_EULER(X)
              REAL(KIND=8), INTENT(OUT) :: X(2)
            END SUBROUTINE SUB_ENDO_EULER
          END INTERFACE 
        END MODULE SUB_ENDO_EULER__genmod
