        !COMPILER-GENERATED INTERFACE MODULE: Wed May 30 13:19:08 2012
        MODULE SUB_HINTER__genmod
          INTERFACE 
            SUBROUTINE SUB_HINTER
            END SUBROUTINE SUB_HINTER
          END INTERFACE 
        END MODULE SUB_HINTER__genmod
