        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 25 10:58:51 2014
        MODULE SUB_EXO_CONSTRAINT__genmod
          INTERFACE 
            SUBROUTINE SUB_EXO_CONSTRAINT(XB)
              REAL(KIND=8) :: XB
            END SUBROUTINE SUB_EXO_CONSTRAINT
          END INTERFACE 
        END MODULE SUB_EXO_CONSTRAINT__genmod
