        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 25 10:58:50 2014
        MODULE SUB_GRIDS__genmod
          INTERFACE 
            SUBROUTINE SUB_GRIDS
            END SUBROUTINE SUB_GRIDS
          END INTERFACE 
        END MODULE SUB_GRIDS__genmod
