        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 01 10:39:18 2013
        MODULE SUB_ERROR__genmod
          INTERFACE 
            SUBROUTINE SUB_ERROR
            END SUBROUTINE SUB_ERROR
          END INTERFACE 
        END MODULE SUB_ERROR__genmod
