        !COMPILER-GENERATED INTERFACE MODULE: Sun May 13 14:56:25 2012
        MODULE SUB_ENDO_ONEDIM__genmod
          INTERFACE 
            SUBROUTINE SUB_ENDO_ONEDIM(XB)
              REAL(KIND=4) :: XB
            END SUBROUTINE SUB_ENDO_ONEDIM
          END INTERFACE 
        END MODULE SUB_ENDO_ONEDIM__genmod
