        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 25 10:58:50 2014
        MODULE SUB_HY_CONSTRAINT__genmod
          INTERFACE 
            SUBROUTINE SUB_HY_CONSTRAINT(XB)
              REAL(KIND=8) :: XB
            END SUBROUTINE SUB_HY_CONSTRAINT
          END INTERFACE 
        END MODULE SUB_HY_CONSTRAINT__genmod
