        !COMPILER-GENERATED INTERFACE MODULE: Thu Jul 04 13:55:56 2013
        MODULE SUB_POLICY__genmod
          INTERFACE 
            SUBROUTINE SUB_POLICY
            END SUBROUTINE SUB_POLICY
          END INTERFACE 
        END MODULE SUB_POLICY__genmod
