        !COMPILER-GENERATED INTERFACE MODULE: Wed Jul 03 17:50:31 2013
        MODULE TEST2__genmod
          INTERFACE 
            SUBROUTINE TEST2(XPRIMES,HPRIMES,CPRIME,KPRIME)
              REAL(KIND=8), INTENT(IN) :: XPRIMES
              REAL(KIND=8), INTENT(IN) :: HPRIMES
              REAL(KIND=8), INTENT(OUT) :: CPRIME
              REAL(KIND=8), INTENT(OUT) :: KPRIME
            END SUBROUTINE TEST2
          END INTERFACE 
        END MODULE TEST2__genmod
