        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 10:18:55 2013
        MODULE TRIANGULATION_SIM__genmod
          INTERFACE 
            SUBROUTINE TRIANGULATION_SIM
            END SUBROUTINE TRIANGULATION_SIM
          END INTERFACE 
        END MODULE TRIANGULATION_SIM__genmod
