        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 25 10:58:51 2014
        MODULE TRIANGULATION__genmod
          INTERFACE 
            SUBROUTINE TRIANGULATION
            END SUBROUTINE TRIANGULATION
          END INTERFACE 
        END MODULE TRIANGULATION__genmod
